set_source_files_properties(/workspace/vllm-ascend/csrc/kernels/bgmv_expand.cpp PROPERTIES COMPILE_OPTIONS --cce-disable-kernel-global-attr-check)
set_source_files_properties(/workspace/vllm-ascend/csrc/kernels/bgmv_shrink.cpp PROPERTIES COMPILE_OPTIONS --cce-disable-kernel-global-attr-check)
set_source_files_properties(/workspace/vllm-ascend/csrc/kernels/get_masked_input_and_mask_kernel.cpp PROPERTIES COMPILE_OPTIONS --cce-disable-kernel-global-attr-check)
set_source_files_properties(/workspace/vllm-ascend/csrc/kernels/sgmv_expand.cpp PROPERTIES COMPILE_OPTIONS --cce-disable-kernel-global-attr-check)
set_source_files_properties(/workspace/vllm-ascend/csrc/kernels/sgmv_shrink.cpp PROPERTIES COMPILE_OPTIONS --cce-disable-kernel-global-attr-check)
set_source_files_properties(/workspace/vllm-ascend/csrc/mla_preprocess/op_kernel/mla_preprocess_kernel.cpp PROPERTIES COMPILE_OPTIONS --cce-disable-kernel-global-attr-check)
set_source_files_properties(/workspace/vllm-ascend/csrc/batch_matmul_transpose/op_kernel/batch_matmul_transpose_kernel.cpp PROPERTIES COMPILE_OPTIONS --cce-disable-kernel-global-attr-check)
