# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/miniconda3/envs/notebook/lib/python3.11/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/miniconda3/envs/notebook/lib/python3.11/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace/vllm-ascend

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace/vllm-ascend

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/miniconda3/envs/notebook/lib/python3.11/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/miniconda3/envs/notebook/lib/python3.11/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/miniconda3/envs/notebook/lib/python3.11/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/miniconda3/envs/notebook/lib/python3.11/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/miniconda3/envs/notebook/lib/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/miniconda3/envs/notebook/lib/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/miniconda3/envs/notebook/lib/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/miniconda3/envs/notebook/lib/python3.11/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/vllm-ascend/CMakeFiles /workspace/vllm-ascend//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/vllm-ascend/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vllm_ascend_kernels_interface

# Build rule for target.
vllm_ascend_kernels_interface: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vllm_ascend_kernels_interface
.PHONY : vllm_ascend_kernels_interface

# fast build rule for target.
vllm_ascend_kernels_interface/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_interface.dir/build.make CMakeFiles/vllm_ascend_kernels_interface.dir/build
.PHONY : vllm_ascend_kernels_interface/fast

#=============================================================================
# Target rules for targets named vllm_ascend_kernels_precompile

# Build rule for target.
vllm_ascend_kernels_precompile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vllm_ascend_kernels_precompile
.PHONY : vllm_ascend_kernels_precompile

# fast build rule for target.
vllm_ascend_kernels_precompile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_precompile.dir/build.make CMakeFiles/vllm_ascend_kernels_precompile.dir/build
.PHONY : vllm_ascend_kernels_precompile/fast

#=============================================================================
# Target rules for targets named vllm_ascend_kernels_preprocess

# Build rule for target.
vllm_ascend_kernels_preprocess: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vllm_ascend_kernels_preprocess
.PHONY : vllm_ascend_kernels_preprocess

# fast build rule for target.
vllm_ascend_kernels_preprocess/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_preprocess.dir/build.make CMakeFiles/vllm_ascend_kernels_preprocess.dir/build
.PHONY : vllm_ascend_kernels_preprocess/fast

#=============================================================================
# Target rules for targets named vllm_ascend_kernels_aic_device

# Build rule for target.
vllm_ascend_kernels_aic_device: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vllm_ascend_kernels_aic_device
.PHONY : vllm_ascend_kernels_aic_device

# fast build rule for target.
vllm_ascend_kernels_aic_device/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_aic_device.dir/build.make CMakeFiles/vllm_ascend_kernels_aic_device.dir/build
.PHONY : vllm_ascend_kernels_aic_device/fast

#=============================================================================
# Target rules for targets named vllm_ascend_kernels_aiv_device

# Build rule for target.
vllm_ascend_kernels_aiv_device: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vllm_ascend_kernels_aiv_device
.PHONY : vllm_ascend_kernels_aiv_device

# fast build rule for target.
vllm_ascend_kernels_aiv_device/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_aiv_device.dir/build.make CMakeFiles/vllm_ascend_kernels_aiv_device.dir/build
.PHONY : vllm_ascend_kernels_aiv_device/fast

#=============================================================================
# Target rules for targets named vllm_ascend_kernels_merge_obj

# Build rule for target.
vllm_ascend_kernels_merge_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vllm_ascend_kernels_merge_obj
.PHONY : vllm_ascend_kernels_merge_obj

# fast build rule for target.
vllm_ascend_kernels_merge_obj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_merge_obj.dir/build.make CMakeFiles/vllm_ascend_kernels_merge_obj.dir/build
.PHONY : vllm_ascend_kernels_merge_obj/fast

#=============================================================================
# Target rules for targets named vllm_ascend_kernels_host

# Build rule for target.
vllm_ascend_kernels_host: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vllm_ascend_kernels_host
.PHONY : vllm_ascend_kernels_host

# fast build rule for target.
vllm_ascend_kernels_host/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_host.dir/build.make CMakeFiles/vllm_ascend_kernels_host.dir/build
.PHONY : vllm_ascend_kernels_host/fast

#=============================================================================
# Target rules for targets named vllm_ascend_kernels_host_stub_obj

# Build rule for target.
vllm_ascend_kernels_host_stub_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vllm_ascend_kernels_host_stub_obj
.PHONY : vllm_ascend_kernels_host_stub_obj

# fast build rule for target.
vllm_ascend_kernels_host_stub_obj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_host_stub_obj.dir/build.make CMakeFiles/vllm_ascend_kernels_host_stub_obj.dir/build
.PHONY : vllm_ascend_kernels_host_stub_obj/fast

#=============================================================================
# Target rules for targets named vllm_ascend_kernels

# Build rule for target.
vllm_ascend_kernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vllm_ascend_kernels
.PHONY : vllm_ascend_kernels

# fast build rule for target.
vllm_ascend_kernels/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels.dir/build.make CMakeFiles/vllm_ascend_kernels.dir/build
.PHONY : vllm_ascend_kernels/fast

#=============================================================================
# Target rules for targets named vllm_ascend_C

# Build rule for target.
vllm_ascend_C: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vllm_ascend_C
.PHONY : vllm_ascend_C

# fast build rule for target.
vllm_ascend_C/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/build
.PHONY : vllm_ascend_C/fast

auto_gen/vllm_ascend_kernels/host_stub.o: auto_gen/vllm_ascend_kernels/host_stub.cpp.o
.PHONY : auto_gen/vllm_ascend_kernels/host_stub.o

# target to build an object file
auto_gen/vllm_ascend_kernels/host_stub.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_host_stub_obj.dir/build.make CMakeFiles/vllm_ascend_kernels_host_stub_obj.dir/auto_gen/vllm_ascend_kernels/host_stub.cpp.o
.PHONY : auto_gen/vllm_ascend_kernels/host_stub.cpp.o

auto_gen/vllm_ascend_kernels/host_stub.i: auto_gen/vllm_ascend_kernels/host_stub.cpp.i
.PHONY : auto_gen/vllm_ascend_kernels/host_stub.i

# target to preprocess a source file
auto_gen/vllm_ascend_kernels/host_stub.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_host_stub_obj.dir/build.make CMakeFiles/vllm_ascend_kernels_host_stub_obj.dir/auto_gen/vllm_ascend_kernels/host_stub.cpp.i
.PHONY : auto_gen/vllm_ascend_kernels/host_stub.cpp.i

auto_gen/vllm_ascend_kernels/host_stub.s: auto_gen/vllm_ascend_kernels/host_stub.cpp.s
.PHONY : auto_gen/vllm_ascend_kernels/host_stub.s

# target to generate assembly for a file
auto_gen/vllm_ascend_kernels/host_stub.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_host_stub_obj.dir/build.make CMakeFiles/vllm_ascend_kernels_host_stub_obj.dir/auto_gen/vllm_ascend_kernels/host_stub.cpp.s
.PHONY : auto_gen/vllm_ascend_kernels/host_stub.cpp.s

csrc/aclnn_torch_adapter/NPUBridge.o: csrc/aclnn_torch_adapter/NPUBridge.cpp.o
.PHONY : csrc/aclnn_torch_adapter/NPUBridge.o

# target to build an object file
csrc/aclnn_torch_adapter/NPUBridge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/aclnn_torch_adapter/NPUBridge.cpp.o
.PHONY : csrc/aclnn_torch_adapter/NPUBridge.cpp.o

csrc/aclnn_torch_adapter/NPUBridge.i: csrc/aclnn_torch_adapter/NPUBridge.cpp.i
.PHONY : csrc/aclnn_torch_adapter/NPUBridge.i

# target to preprocess a source file
csrc/aclnn_torch_adapter/NPUBridge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/aclnn_torch_adapter/NPUBridge.cpp.i
.PHONY : csrc/aclnn_torch_adapter/NPUBridge.cpp.i

csrc/aclnn_torch_adapter/NPUBridge.s: csrc/aclnn_torch_adapter/NPUBridge.cpp.s
.PHONY : csrc/aclnn_torch_adapter/NPUBridge.s

# target to generate assembly for a file
csrc/aclnn_torch_adapter/NPUBridge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/aclnn_torch_adapter/NPUBridge.cpp.s
.PHONY : csrc/aclnn_torch_adapter/NPUBridge.cpp.s

csrc/aclnn_torch_adapter/NPUStorageImpl.o: csrc/aclnn_torch_adapter/NPUStorageImpl.cpp.o
.PHONY : csrc/aclnn_torch_adapter/NPUStorageImpl.o

# target to build an object file
csrc/aclnn_torch_adapter/NPUStorageImpl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/aclnn_torch_adapter/NPUStorageImpl.cpp.o
.PHONY : csrc/aclnn_torch_adapter/NPUStorageImpl.cpp.o

csrc/aclnn_torch_adapter/NPUStorageImpl.i: csrc/aclnn_torch_adapter/NPUStorageImpl.cpp.i
.PHONY : csrc/aclnn_torch_adapter/NPUStorageImpl.i

# target to preprocess a source file
csrc/aclnn_torch_adapter/NPUStorageImpl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/aclnn_torch_adapter/NPUStorageImpl.cpp.i
.PHONY : csrc/aclnn_torch_adapter/NPUStorageImpl.cpp.i

csrc/aclnn_torch_adapter/NPUStorageImpl.s: csrc/aclnn_torch_adapter/NPUStorageImpl.cpp.s
.PHONY : csrc/aclnn_torch_adapter/NPUStorageImpl.s

# target to generate assembly for a file
csrc/aclnn_torch_adapter/NPUStorageImpl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/aclnn_torch_adapter/NPUStorageImpl.cpp.s
.PHONY : csrc/aclnn_torch_adapter/NPUStorageImpl.cpp.s

csrc/batch_matmul_transpose/op_host/tiling/tiling_data.o: csrc/batch_matmul_transpose/op_host/tiling/tiling_data.cpp.o
.PHONY : csrc/batch_matmul_transpose/op_host/tiling/tiling_data.o

# target to build an object file
csrc/batch_matmul_transpose/op_host/tiling/tiling_data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/batch_matmul_transpose/op_host/tiling/tiling_data.cpp.o
.PHONY : csrc/batch_matmul_transpose/op_host/tiling/tiling_data.cpp.o

csrc/batch_matmul_transpose/op_host/tiling/tiling_data.i: csrc/batch_matmul_transpose/op_host/tiling/tiling_data.cpp.i
.PHONY : csrc/batch_matmul_transpose/op_host/tiling/tiling_data.i

# target to preprocess a source file
csrc/batch_matmul_transpose/op_host/tiling/tiling_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/batch_matmul_transpose/op_host/tiling/tiling_data.cpp.i
.PHONY : csrc/batch_matmul_transpose/op_host/tiling/tiling_data.cpp.i

csrc/batch_matmul_transpose/op_host/tiling/tiling_data.s: csrc/batch_matmul_transpose/op_host/tiling/tiling_data.cpp.s
.PHONY : csrc/batch_matmul_transpose/op_host/tiling/tiling_data.s

# target to generate assembly for a file
csrc/batch_matmul_transpose/op_host/tiling/tiling_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/batch_matmul_transpose/op_host/tiling/tiling_data.cpp.s
.PHONY : csrc/batch_matmul_transpose/op_host/tiling/tiling_data.cpp.s

csrc/camem_allocator.o: csrc/camem_allocator.cpp.o
.PHONY : csrc/camem_allocator.o

# target to build an object file
csrc/camem_allocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/camem_allocator.cpp.o
.PHONY : csrc/camem_allocator.cpp.o

csrc/camem_allocator.i: csrc/camem_allocator.cpp.i
.PHONY : csrc/camem_allocator.i

# target to preprocess a source file
csrc/camem_allocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/camem_allocator.cpp.i
.PHONY : csrc/camem_allocator.cpp.i

csrc/camem_allocator.s: csrc/camem_allocator.cpp.s
.PHONY : csrc/camem_allocator.s

# target to generate assembly for a file
csrc/camem_allocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/camem_allocator.cpp.s
.PHONY : csrc/camem_allocator.cpp.s

csrc/torch_binding.o: csrc/torch_binding.cpp.o
.PHONY : csrc/torch_binding.o

# target to build an object file
csrc/torch_binding.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/torch_binding.cpp.o
.PHONY : csrc/torch_binding.cpp.o

csrc/torch_binding.i: csrc/torch_binding.cpp.i
.PHONY : csrc/torch_binding.i

# target to preprocess a source file
csrc/torch_binding.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/torch_binding.cpp.i
.PHONY : csrc/torch_binding.cpp.i

csrc/torch_binding.s: csrc/torch_binding.cpp.s
.PHONY : csrc/torch_binding.s

# target to generate assembly for a file
csrc/torch_binding.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/torch_binding.cpp.s
.PHONY : csrc/torch_binding.cpp.s

csrc/torch_binding_meta.o: csrc/torch_binding_meta.cpp.o
.PHONY : csrc/torch_binding_meta.o

# target to build an object file
csrc/torch_binding_meta.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/torch_binding_meta.cpp.o
.PHONY : csrc/torch_binding_meta.cpp.o

csrc/torch_binding_meta.i: csrc/torch_binding_meta.cpp.i
.PHONY : csrc/torch_binding_meta.i

# target to preprocess a source file
csrc/torch_binding_meta.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/torch_binding_meta.cpp.i
.PHONY : csrc/torch_binding_meta.cpp.i

csrc/torch_binding_meta.s: csrc/torch_binding_meta.cpp.s
.PHONY : csrc/torch_binding_meta.s

# target to generate assembly for a file
csrc/torch_binding_meta.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_C.dir/build.make CMakeFiles/vllm_ascend_C.dir/csrc/torch_binding_meta.cpp.s
.PHONY : csrc/torch_binding_meta.cpp.s

vllm_ascend_kernels_stub.o: vllm_ascend_kernels_stub.cpp.o
.PHONY : vllm_ascend_kernels_stub.o

# target to build an object file
vllm_ascend_kernels_stub.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_interface.dir/build.make CMakeFiles/vllm_ascend_kernels_interface.dir/vllm_ascend_kernels_stub.cpp.o
.PHONY : vllm_ascend_kernels_stub.cpp.o

vllm_ascend_kernels_stub.i: vllm_ascend_kernels_stub.cpp.i
.PHONY : vllm_ascend_kernels_stub.i

# target to preprocess a source file
vllm_ascend_kernels_stub.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_interface.dir/build.make CMakeFiles/vllm_ascend_kernels_interface.dir/vllm_ascend_kernels_stub.cpp.i
.PHONY : vllm_ascend_kernels_stub.cpp.i

vllm_ascend_kernels_stub.s: vllm_ascend_kernels_stub.cpp.s
.PHONY : vllm_ascend_kernels_stub.s

# target to generate assembly for a file
vllm_ascend_kernels_stub.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vllm_ascend_kernels_interface.dir/build.make CMakeFiles/vllm_ascend_kernels_interface.dir/vllm_ascend_kernels_stub.cpp.s
.PHONY : vllm_ascend_kernels_stub.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... vllm_ascend_kernels_aic_device"
	@echo "... vllm_ascend_kernels_aiv_device"
	@echo "... vllm_ascend_kernels_host"
	@echo "... vllm_ascend_kernels_merge_obj"
	@echo "... vllm_ascend_kernels_precompile"
	@echo "... vllm_ascend_kernels_preprocess"
	@echo "... vllm_ascend_C"
	@echo "... vllm_ascend_kernels"
	@echo "... vllm_ascend_kernels_host_stub_obj"
	@echo "... vllm_ascend_kernels_interface"
	@echo "... auto_gen/vllm_ascend_kernels/host_stub.o"
	@echo "... auto_gen/vllm_ascend_kernels/host_stub.i"
	@echo "... auto_gen/vllm_ascend_kernels/host_stub.s"
	@echo "... csrc/aclnn_torch_adapter/NPUBridge.o"
	@echo "... csrc/aclnn_torch_adapter/NPUBridge.i"
	@echo "... csrc/aclnn_torch_adapter/NPUBridge.s"
	@echo "... csrc/aclnn_torch_adapter/NPUStorageImpl.o"
	@echo "... csrc/aclnn_torch_adapter/NPUStorageImpl.i"
	@echo "... csrc/aclnn_torch_adapter/NPUStorageImpl.s"
	@echo "... csrc/batch_matmul_transpose/op_host/tiling/tiling_data.o"
	@echo "... csrc/batch_matmul_transpose/op_host/tiling/tiling_data.i"
	@echo "... csrc/batch_matmul_transpose/op_host/tiling/tiling_data.s"
	@echo "... csrc/camem_allocator.o"
	@echo "... csrc/camem_allocator.i"
	@echo "... csrc/camem_allocator.s"
	@echo "... csrc/torch_binding.o"
	@echo "... csrc/torch_binding.i"
	@echo "... csrc/torch_binding.s"
	@echo "... csrc/torch_binding_meta.o"
	@echo "... csrc/torch_binding_meta.i"
	@echo "... csrc/torch_binding_meta.s"
	@echo "... vllm_ascend_kernels_stub.o"
	@echo "... vllm_ascend_kernels_stub.i"
	@echo "... vllm_ascend_kernels_stub.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

